spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-heyuan.aliyuncs.com
      access-key: LTAI4FzW3DC7PFBu29X6dLM4
      secret-key: RvaX1en6NP5pUwkhm8e3CYAdRpKQOl
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root 
    password: root
  redis:
    host: 192.168.230.133
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8888
